baseURL = "https://blog.boardgamerweekly.com/"
languageCode = "en-us"
title = "BGW blog"
copyright = "BoardGamerWeekly"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
disqusShortname = "bgw-blog"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "images/favicon.png"
  description = "Resolving shelf of shame"
  facebook = "https://www.facebook.com/boardgamerweekly"
  twitter = "https://twitter.com/BoardGamerWkly"
  instagram = "https://www.instagram.com/boardgamerweekly/"
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-near-black"
  featured_image = "/images/boardgamerweekly-featured.jpg"
  recent_posts_number = 2
  show_reading_time = true
  custom_css = ["css/custom.css"]

[permalinks]
  posts = "/:year/:month/:title/"
